Add Taiwan translation for README.md file
rocky-linux/rocky pull request #80
Opened 2020-12-14 16:43 UTC by evshary

Add Taiwan translation for README.md file

2020-12-14 16:54 UTC, toto6038 requested changes

2020-12-14 16:54 UTC, toto6038 commented on README.zh_TW.md
> +為了因應 CentOS 發展方向的改變，Rocky Linux 會是一個基於社群所開發的企業級作業系統，能與 RHEL 發行版 100％ 完全兼容。
"compatible" should be 相容 instead of 兼容

2020-12-15 01:53 UTC, evshary commented on README.zh_TW.md
> +為了因應 CentOS 發展方向的改變，Rocky Linux 會是一個基於社群所開發的企業級作業系統，能與 RHEL 發行版 100％ 完全兼容。
@toto6038 Thanks for your suggestion. I've updated the documentation.

2020-12-15 01:59 UTC, evshary commented
@toto6038 We're happy to see Taiwanese in the Rocky Linux community. If you have any comments, please let us know.
BTW, we've created a [website](https://rockylinux.tw/) to bridge Rocky Linux and Taiwan's local community. Feel free to PR to the repo if you have anything worthy to share with the community.

2020-12-15 02:10 UTC, toto6038 commented
Glad to see that! It's fast to have a Taiwan domain. Maybe we need a TW telegram group?

2020-12-15 07:10 UTC, evshary commented
Well, to be honest, I'm a little sad that #81 is created and merged instead of discussing and modifying this earlier PR.
But that's fine. I'll close this PR.

2020-12-15 07:10 UTC, closed without merging

2020-12-15 15:09 UTC, toto6038 commented
Ah... sorry for that

2020-12-15 15:54 UTC, toto6038 commented
Ah... sorry for that. You've done a great job!!! Appreciate for your work :)